version: '3.1'

services:
  prestashop:
    image: prestashop/prestashop:latest
    restart: always
    ports:
      - 80:80
    environment:
      - DB_SERVER=prestashop_db
      - DB_NAME=prestashop
      - DB_USER=root
      - DB_PASSWD=secret
    volumes:
      - /data/prestashop:/var/www/html
    depends_on:
      - prestashop_db
    networks:
      - prestashop_network

  prestashop_db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=prestashop
    volumes:
      - /data/prestashop_DB:/var/lib/mysql
    networks:
      - prestashop_network

networks:
  prestashop_network:
    driver: bridge
